version: '3.8'

services:

  auth:
    build:
      context: ./auth_service
    networks:
      - klink_net
    ports:
      - 8000:8000
    environment:
      - HOST_IP=0.0.0.0
      - HOST_PORT=8000
      - JWT_SECRET=secret
      - USER_SERVICE_URL=http://user:8001

  user:
    build:
      context: ./user_service
    networks:
      - klink_net
    ports:
      - 8001:8001
    environment:
      - DATABASE_URL=postgres://test:test@user_db:5432/test
      - HOST_PORT=8001
      - HOST_IP=0.0.0.0

  user_db:
    image: postgres:latest
    networks:
      - klink_net
    volumes:
      - user_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

networks:
  klink_net:


volumes:
  user_data:
